name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build (production)
        # On force la sortie dans dist/portfolio_angular et on met le base-href
        run: npm run build -- --output-path=dist/portfolio_angular --base-href=/portfolio_angular/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/portfolio_angular

