name: Build and Deploy to GitHub Pages

# Donner explicitement les permissions nécessaires pour écrire dans la branche
permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build (production)
        # On force la sortie dans dist/portfolio_angular et on met le base-href
        run: npm run build -- --output-path=dist/portfolio_angular --base-href=/portfolio_angular/

      - name: List build output (debug)
        run: ls -la dist || echo "dist/ directory not found"

      - name: Flatten `browser` output if present
        # Si Angular SSR produit un sous-dossier `browser` (ex: dist/.../browser), on copie son contenu à la racine de output-path
        run: |
          if [ -d "dist/portfolio_angular/browser" ]; then
            echo "Found browser folder, copying its content to dist/portfolio_angular/";
            cp -r dist/portfolio_angular/browser/. dist/portfolio_angular/ || true;
            echo "Copy done.";
          else
            echo "No browser folder detected, nothing to copy.";
          fi

      - name: Verify final publish dir (debug)
        run: |
          ls -la dist/portfolio_angular || echo "publish dir missing: dist/portfolio_angular"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Par défaut on utilise le GITHUB_TOKEN fourni par GitHub Actions (doit fonctionner si le workflow a les permissions 'contents: write' et 'pages: write')
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Si tu préfères utiliser un Personal Access Token (ex: pour pousser sur un repo parent/fork), crée un secret GH_PAGES_TOKEN et décommente la ligne ci-dessous
          # personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./dist/portfolio_angular
          publish_branch: gh-pages
          # (keep_history option removed to avoid static-checker warning)
